version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.12  # Adjust this to your Python version
    commands:
      - echo "Installing Python dependencies"
      - python -m venv venv --copies
      - . venv/bin/activate
      - pip install -r requirements.txt
 
  pre_build:
    commands:
      - echo "Running pre-build steps like database migrations"
      - python manage.py migrate  # Only if you have a database setup for the build environment
      - python manage.py collectstatic --noinput
 
  build:
    commands:
      - echo "Running tests"
      - python manage.py test  # Replace or remove if you have different test commands
 
  post_build:
    commands:
      - echo "Build completed on date"
 
artifacts:
  files:
    - '**/*'  # Specifies the files to include in the build artifact