# Generated by Django 5.0 on 2023-12-07 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='imagepost',
            field=models.ImageField(default='default.jpg', upload_to='posts', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
