# Generated by Django 5.0 on 2023-12-07 01:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmodel_imagepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='location',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
