# Generated by Django 5.0 on 2023-12-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postmodel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
